---
# Install required packages on the host

- name: "Disable all apt recommendations and suggestions"
  copy:
    src: "99local"
    dest: "/etc/apt/apt.conf.d/99local"
    owner: root
    group: root
    mode: 0644
  tags: ['config']
    

- name: "Uninstall rsyslog"
  apt: {name: "rsyslog", state: absent, purge: yes, autoremove: yes}
  when: remove_rsyslog|d(false)
  tags: ['cleanup']

- name: "Remove unneeded Ubuntu packages"
  apt:
    name:
      - "accountsservice"
      - "byobu"
      - "fwupd"
      - "libfwupd2"
      - "haveged"
      - "lvm2"
      - "mdadm"
      - "multipath-tools"
      - "packagekit"
      - "plymouth"
      - "snapd"
      - "ufw"
    state: absent
    purge: yes
    autoremove: yes
  when: ansible_facts['distribution'] == "Ubuntu"
  tags: ['cleanup']

- name: "Upgrade the system"
  apt:
    update_cache: yes
    upgrade: dist
  tags: ['update']

- name: Install useful tools and programs
  become: true
  ansible.builtin.package:
    name:
      - curl
      - nano
      - sudo
      - htop
      - atop
      - screen
      - net-tools
      - sysstat
      - iotop
      - python3-pip
    state: present
    update_cache: true
  tags: ['packages']

- name: Ensure prerequisite OS packages for Python Docker SDK are installed
  ansible.builtin.apt: # Or ansible.builtin.package
    name:
      - python3-pip      # Still good to have pip for other non-system critical packages if needed later
      - python3-docker   # This is the system package for Docker SDK
      - python3-requests # This is the system package for requests
      # - python3-yaml     # For PyYAML, often python3-yaml or python3-ruamel.yaml
      # - python3-jsondiff # If available and needed
    state: present
    update_cache: yes # Run apt update before installing
  when: ansible_os_family == "Debian" # Or more specific like ansible_distribution == "Ubuntu" and ansible_distribution_version >= "23.04"
  # Add a retry for apt as well
  retries: 3
  delay: 10
  register: apt_install_result
  until: apt_install_result is success

- name: "Install man pages"
  apt:
    name: ["man-db", "manpages"]
    state: present
  tags: ['packages']
